### LocalHost request
GET http://localhost:8080

### LocalHost request
GET http://localhost:8080/professional
# the request above returns a json object with all professional data for Nathan Birch. No database is connected.

### GET all contacts
GET http://localhost:8080/contacts

### GET a single contacts by ID
GET http://localhost:8080/contacts/696be7b1f573a669c8752661 

### GET a single contacts by ID
GET http://localhost:8080/contacts/696be7d8f573a669c8752663 

### GET a single contacts by ID
GET http://localhost:8080/contacts/696be7eff573a669c8752665 

### POST create contact
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "Martha",
  "lastName": "Stewart",
  "email": "m.stewart@gmail.com",
  "favoriteColor": "yellow",
  "birthday": "11/07/1957"
}

### PUT update contact
PUT http://localhost:8080/contacts/6973ba563b6d17426391bc42
Content-Type: application/json

{
  "firstName": "Martha",
  "lastName": "Stewart",
  "email": "martha.stewart@gmail.com",
  "favoriteColor": "pink",
  "birthday": "11/07/1957"
}

### PUT update contact
DELETE http://localhost:8080/contacts/6973ba563b6d17426391bc42
