### Root test 
GET http://localhost:8080/
Content-Type: application/json


### Get all audiobooks
GET http://localhost:8080/audiobooks
Content-Type: application/json


### Get audiobook by ID
# Replace {{id}} with a real MongoDB _id
GET http://localhost:8080/audiobooks/6987a0fb3ee9c679f38e4fd8
Content-Type: application/json


### Create a new audiobook
POST http://localhost:8080/audiobooks
Content-Type: application/json

{
  "title": "Scoobie-Doo",
  "author": "Dtephenie Meyer",
  "listening_length": "20 hours and 28 minutes",
  "publisher": "Listening Library",
  "narrator": "Ilyana Kadushin, Matt Walters",
  "ASIN": "B001FD6RLM",
  "audio_release_date": "September 02, 2008",
  "description": "To be irrevocably in love with a vampire is both fantasy and nightmare woven into a dangerously heightened reality for Bella Swan. Pulled in one direction by her intense passion for Edward Cullen, and in another by her profound connection to werewolf Jacob Black, she has endured a tumultuous year of temptation , loss, and strife to reach the ultimate turning point. Her imminent choice to either join the dark but seductive world of immortals or pursue a fully human life has become the thread from which the date of two tribes hangs."
}



### Update an audiobook
PUT http://localhost:8080/audiobooks/6987a0fb3ee9c679f38e4fd8
Content-Type: application/json

{
  "title": "Scooby-Doo!",
  "author": "Stephenie Meyer",
  "listening_length": "20 hours and 28 minutes",
  "publisher": "Listening Library",
  "narrator": "Ilyana Kadushin, Matt Walters",
  "ASIN": "B001FD6RLM",
  "audio_release_date": "September 02, 2008",
  "description": "To be irrevocably in love with a vampire is both fantasy and nightmare woven into a dangerously heightened reality for Bella Swan. Pulled in one direction by her intense passion for Edward Cullen, and in another by her profound connection to werewolf Jacob Black, she has endured a tumultuous year of temptation , loss, and strife to reach the ultimate turning point. Her imminent choice to either join the dark but seductive world of immortals or pursue a fully human life has become the thread from which the date of two tribes hangs."
}


### Delete an audiobook
DELETE http://localhost:8080/audiobooks/6987a0fb3ee9c679f38e4fd8
Content-Type: application/json