### Root test (optional)
GET http://localhost:8080/
Content-Type: application/json


### Get all audiobooks
GET http://localhost:8080/audiobooks
Content-Type: application/json


### Get audiobook by ID
# Replace {{id}} with a real MongoDB _id
GET http://localhost:8080/audiobooks/69871950bb86969351ee40c6
Content-Type: application/json


### Create a new audiobook
POST http://localhost:8080/audiobooks
Content-Type: application/json

{
  "title": "Twilight",
  "author": "Stephenie Meyer",
  "listening_length": "12 hours and 51 minutes",
  "publisher": "Listening Library",
  "narrator": "Ilyana Kadushin",
  "ASIN": "B000BO2D64",
  "audio_release_date": "October 05, 2005",
  "description": "About three things I was absolutely positive: First, Edward was a vampire. Second, there was a part of him–and I didn’t know how dominant that part might be–that thirsted for my blood. And third, I was unconditionally and irrevocably in love with him."
}


### Update an audiobook
# PUT http://localhost:8080/audiobooks/698717e9bb86969351ee40c5
# Content-Type: application/json

# {
#   "title": "Twilight",
#   "author": "Stephenie Meyer",
#   "listening_length": "12 hours and 51 minutes",
#   "publisher": "Listening Library",
#   "narrator": "Ilyana Kadushin",
#   "ASIN": "B000BO2D64",
#   "audio_release_date": "October 05, 2005",
#   "description": "About three things I was absolutely positive: First, Edward was a vampire. Second, there was a part of him–and I didn’t know how dominant that part might be–that thirsted for my blood. And third, I was unconditionally and irrevocably in love with him."
# }


### Delete an audiobook
# DELETE http://localhost:8080/audiobooks/698717e9bb86969351ee40c5
# Content-Type: application/json